//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumerinfosummary
    {
        public int idConsumer { get; set; }
        public int Consumer_ID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string IDnumber { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string gender { get; set; }
        public string maritalStatus { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<decimal> claimRate { get; set; }
        public string RiskCategory { get; set; }
        public Nullable<int> numUnprocessed { get; set; }
        public string purchasedProducts { get; set; }
        public string purchasedProductIDs { get; set; }
    }
}
