//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumergroup
    {
        public int idconsumerGroups { get; set; }
        public string attributes { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<decimal> claimRate { get; set; }
    }
}
