//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unprocessedapplication
    {
        public int ActiveProductItems_ID { get; set; }
        public Nullable<int> age { get; set; }
        public int Consumer_ID { get; set; }
        public string gender { get; set; }
        public string maritalStatus { get; set; }
        public string productName { get; set; }
        public long numPurchases { get; set; }
        public Nullable<int> numClaims { get; set; }
        public Nullable<decimal> claimRate { get; set; }
    }
}
