//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNanoFinAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database_nanofinEntities : DbContext
    {
        public database_nanofinEntities()
            : base("name=database_nanofinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activeproductitem> activeproductitems { get; set; }
        public virtual DbSet<claimuploaddocument> claimuploaddocuments { get; set; }
        public virtual DbSet<consumer> consumers { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<insuranceproduct> insuranceproducts { get; set; }
        public virtual DbSet<insurancetype> insurancetypes { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<notificationlog> notificationlogs { get; set; }
        public virtual DbSet<processapplication> processapplications { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productprovider> productproviders { get; set; }
        public virtual DbSet<productproviderpayment> productproviderpayments { get; set; }
        public virtual DbSet<productredemptionlog> productredemptionlogs { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<reseller> resellers { get; set; }
        public virtual DbSet<systemadmin> systemadmins { get; set; }
        public virtual DbSet<transactiontype> transactiontypes { get; set; }
        public virtual DbSet<unittype> unittypes { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usertype> usertypes { get; set; }
        public virtual DbSet<validator> validators { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<vouchertransaction> vouchertransactions { get; set; }
        public virtual DbSet<vouchertype> vouchertypes { get; set; }
        public virtual DbSet<productsalespermonth> productsalespermonths { get; set; }
        public virtual DbSet<claim> claims { get; set; }
        public virtual DbSet<claimtemplate> claimtemplates { get; set; }
    }
}
